version: "3.6"

services:
  mqtt-server:
    image: ghcr.io/everest/everest-demo/mqtt-server:0.0.3
    logging:
      driver: none

  manager:
    image: ghcr.io/everest/everest-demo/manager:0.0.3
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    ports:
      - 8849:8849
    entrypoint: "sh ./build/run-scripts/run-sil.sh"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
