version: "3.6"

services:
  mqtt-server:
    build: ./mosquitto
    image: ghcr.io/us-joet/everest-demo/mqtt-server:0.0.1
    platform: linux/x86_64
    logging:
      driver: none

  manager:
    build: ./manager
    platform: linux/x86_64
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    entrypoint: "sh ./build/run-scripts/run-sil-ocpp.sh"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  ocpp-db:
    image: mariadb:10.4.30
    command: [ "--datadir", "/var/lib/mysql-no-volume" ]
    ports:
      - 13306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ocpp-db
      MYSQL_USER: ocpp
      MYSQL_PASSWORD: ocpp

  steve:
    build: ./steve
    ports:
      - 8180:8180
      - 8443:8443
    depends_on:
      - ocpp-db

  nodered:
    build: ./nodered
    image: ghcr.io/us-joet/everest-demo/nodered:0.0.2
    depends_on:
      - mqtt-server
    ports:
      - 1880:1880
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/config/config-sil-two-evse-flow.json
