version: "3.6"

services:
  mqtt-server:
    image: ghcr.io/us-joet/everest-demo/mqtt-server:${TAG}
    logging:
      driver: none

  manager:
    image: ghcr.io/us-joet/everest-demo/manager:${TAG}
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    working_dir: /ext/source/tests
    entrypoint: "sh ./run-test.sh"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
