version: "3.6"

services:
  mqtt-server:
    image: ghcr.io/shankari/mqtt-server:0.0.1
    logging:
      driver: none

  manager:
    image: ghcr.io/shankari/manager:0.0.1
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    entrypoint: "sh ./build/run-scripts/run-sil.sh"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  node-red:
    image: ghcr.io/shankari/nodered:0.0.1
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/config/config-sil-flow.json
    ports:
      - 1880:1880
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
