version: "3.6"

services:
  mqtt-server:
    image: ghcr.io/shankari/everest-demo/mqtt-server:0.0.1
    logging:
      driver: none

  ocpp-db:
    image: ghcr.io/shankari/everest-demo/ocpp-db-compiled:0.0.1
    command: [ "--datadir", "/var/lib/mysql-no-volume" ]
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ocpp-db
      MYSQL_USER: ocpp
      MYSQL_PASSWORD: ocpp

  steve:
    image: ghcr.io/shankari/everest-demo/steve-compiled:0.0.1
    ports:
      - 8180:8180
    depends_on:
      - ocpp-db

  manager:
    image: ghcr.io/shankari/everest-demo/manager:0.0.2
    depends_on:
      - mqtt-server
      - steve
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    entrypoint: "sh ./build/run-scripts/run-sil-ocpp.sh"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  node-red:
    image: ghcr.io/shankari/everest-demo/nodered:0.0.1
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/config/config-sil-flow.json
    ports:
      - 1880:1880
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
