name: cicd

on:
  pull_request:
    branches:
      - 'main'

jobs:
  docker-build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - host_namespace: ghcr.io/us-joet/everest-demo
            image_name: manager
            context: ./manager
          - host_namespace: ghcr.io/us-joet/everest-demo
            image_name: mqtt-server
            context: ./mosquitto
          - host_namespace: ghcr.io/us-joet/everest-demo
            image_name: nodered
            context: ./nodered

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure Docker image version is not referencing an existing release
        id: docker-image-version-check
        run: |
          if ! [[ -s .docker_image_version  ]]; then
            echo 'Error: No .docker_image_version file found.'
            exit 1
          fi

          SEMVER="$(cat .docker_images_version)"
          if git show-ref --tags --verify --quiet "refs/tags/v${SEMVER}"; then
            echo "Error: The tag 'v${SEMVER}' is already a GitHub release.'
            echo '       Please update the version in .docker_image_version'
            exit 1
          else
            echo "SEMVER=${SEMVER}" >> "${GITHUB_OUTPUT}"
          fi

      - name: Set Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.host_namespace }}/${{ matrix.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=${{ steps.docker-image-version-check.outputs.SEMVER }}

      - name: Log into GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.image_name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.image_name }}
